version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sunny/frontend_web
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sunny/backend_server
    ports:
      - "1234:1234"
    volumes:
      - ./backend:/usr/src/app
